# Generated by Django 5.2.3 on 2025-06-26 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0002_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
