# Generated by Django 5.2.3 on 2025-06-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0003_remove_board_member_count_remove_board_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='kanban_app.board'),
            preserve_default=False,
        ),
    ]
